spring.application.name=keeply

kakao.client.secret=2622bfcc7f0d3ab872d0d350c0676b79
kakao.client.id=5aaaa5bc68e0ff4071da1a4cc772e695

jwt.secret=testsecret
jwt.access-token.expiration=3600
jwt.refresh-token.expiration=3600*24*14
