name: Deploy Gradle to dev-server

on:
  push:
    branches: [develop]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create credentials
        run: |
          mkdir -p credentials
          printf "%s" "${{ secrets.FIREBASE_CREDENTIAL_JSON }}" | base64 --decode > credentials/firebase.json
          printf "%s" "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" | base64 --decode > credentials/vision.json
      - name: Upload credentials artifact
        uses: actions/upload-artifact@v4
        with:
          name: credentials
          path: credentials

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build -x test
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: keeply
          path: build/libs/keeply-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: keeply
          path: build/libs/
      - name: Download credentials
        uses: actions/download-artifact@v4
        with:
          name: credentials
          path: ./credentials
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/keeply-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.DEV_EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/keeply-0.0.1-SNAPSHOT.jar
          scp -i private_key.pem -o StrictHostKeyChecking=no ./credentials/* ${{ secrets.EC2_USERNAME }}@${{ secrets.DEV_EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/credentials/
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.DEV_EC2_HOST }} "pgrep java | xargs -r kill -9; /home/${{ secrets.EC2_USERNAME }}/deploy.sh"
          rm -f private_key.pem
